name: QA Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Auto Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Build Auto Test
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      id: run_tests
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: 1
        body: This is a multi-line test comment